### ISSUE TITLE
Install onnx-tensorrt  in JetPack and Isaac ROS 3.2 "python3 setup.py install"(readme_jetson.md) gave  CUDA error code=35(b'cudaErrorInsufficientDriver')

### ISSUE THREAD

**Issue by YOODS-Xu** [NVlabs/FoundationStereo#209]
According to readme_jetson.md,
Install onnx-tensorrt, running python3 setup.py install gave the following error.

python3 setup.py install
Traceback (most recent call last):
  File "/onnx-tensorrt/setup.py", line 5, in <module>
    import onnx_tensorrt
  File "/onnx-tensorrt/onnx_tensorrt/__init__.py", line 5, in <module>
    from . import backend
  File "/onnx-tensorrt/onnx_tensorrt/backend.py", line 4, in <module>
    from .tensorrt_engine import Engine
  File "/onnx-tensorrt/onnx_tensorrt/tensorrt_engine.py", line 57, in <module>
    cuda_call(cudart.cudaFree(0))
  File "/onnx-tensorrt/onnx_tensorrt/tensorrt_engine.py", line 43, in cuda_call
    raise RuntimeError(
RuntimeError: CUDA error code=35(b'cudaErrorInsufficientDriver')

Hardware: JetSon AGX Orin 64G
JetPack 6.1
Isaac ROS 3.2

The link [Developer Environment Setup](https://nvidia-isaac-ros.github.io/getting_started/dev_env_setup.html)
 in readme_jetson.md is broken.
I set up the environment according to [this page](https://nvidia-isaac-ros.github.io/v/release-3.2/getting_started/dev_env_setup.html)

I found JetPack's GPU driver is 540, but according to readme.md,  it said in x86, Build docker (tested on NVIDIA Driver Version: 560.35.03, CUDA Version: 12.6)
https://github.com/NVlabs/FoundationStereo/blob/master/readme.md

May I ask which versions of JetPack and Isaac ROS are appropriate?

**Comment by zhanghua7099** [comment]
Hi! Have you solved this problem?

**Comment by YOODS-Xu** [comment]
因为有几个急项目，一直没时间。大概明天能够回到这个项目。您解决这个问题了吗？

**Comment by YOODS-Xu** [comment]
已经解决这个问题了。请参考
https://github.com/NVlabs/FoundationStereo/issues/207#issuecomment-3569321772
